spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8090
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: never
